apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  labels:
    app: landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
      - name: landing-page
        image: adipurnamk/landing-page:latest # This will be overridden by overlays
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "development"  # This will be overridden by overlays