version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_EMAILJS_SERVICE_ID=your_service_id
      - VITE_EMAILJS_TEMPLATE_ID=your_template_id
      - VITE_EMAILJS_USER_ID=your_user_id
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src 