apiVersion: v1
kind: Service
metadata:
  name: "{{ include "landing-page.fullname" . }}"
  labels:
    {{- include "landing-page.labels" . | nindent 4 }}
spec:
  type: "{{ .Values.service.type }}"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "landing-page.selectorLabels" . | nindent 4 }}
