apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: landing-page
        env:
        - name: ENVIRONMENT
          value: "development"